### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by benekastah** [seedifferently/pyramid_assetmutator#1]
This is what I get when trying to install:

```
$ pip install pyramid_assetcompiler
Downloading/unpacking pyramid-assetcompiler
  Could not find any downloads that satisfy the requirement pyramid-assetcompiler
No distributions at all found for pyramid-assetcompiler
Storing complete log in /Users/benekastah/.pip/pip.log
```

I'm running Python 3.3

**Comment by seedifferently** [comment]
Thanks for your interest in this project...unfortunately it's still in an experimental phase and I haven't actually uploaded it to the package index.

If you _really_ want to tinker around with it, you can try installing via one of the download links, for example:

```
pip install https://github.com/seedifferently/pyramid_assetcompiler/archive/master.zip
```
