### ISSUE TITLE
Detect Changes in Imported Files

### ISSUE THREAD

**Issue by jonahbron** [seedifferently/pyramid_assetmutator#7]
Asset Mutator is working great for me, the only real issue left that I face is importing files. If you modify an imported file, it changes neither the modified date, nor the checksum of the original file that Asset Mutator examines.  Any ideas on how we could get it to detect changes in imported files?

**Comment by seedifferently** [comment]
v1.0b1 introduces a new `always_remutate` setting that can be utilized in development environments to make sure imports are always reprocessed.
